// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CreateGadgetReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from CreateGadgetReason.proto</summary>
  public static partial class CreateGadgetReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for CreateGadgetReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateGadgetReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDcmVhdGVHYWRnZXRSZWFzb24ucHJvdG8SDW1pSG9tby5Qcm90b3MqdwoS",
            "Q3JlYXRlR2FkZ2V0UmVhc29uEhYKEkNSRUFURV9HQURHRVRfTk9ORRAAEhgK",
            "FENSRUFURV9HQURHRVRfUExBWUVSEAESGQoVQ1JFQVRFX0dBREdFVF9NSVNT",
            "SU9OEAISFAoQQ1JFQVRFX0dBREdFVF9HTRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MiHomo.Protos.CreateGadgetReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CreateGadgetReason {
    [pbr::OriginalName("CREATE_GADGET_NONE")] CreateGadgetNone = 0,
    [pbr::OriginalName("CREATE_GADGET_PLAYER")] CreateGadgetPlayer = 1,
    [pbr::OriginalName("CREATE_GADGET_MISSION")] CreateGadgetMission = 2,
    [pbr::OriginalName("CREATE_GADGET_GM")] CreateGadgetGm = 3,
  }

  #endregion

}

#endregion Designer generated code
