// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GadgetGuestBanDrop.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from GadgetGuestBanDrop.proto</summary>
  public static partial class GadgetGuestBanDropReflection {

    #region Descriptor
    /// <summary>File descriptor for GadgetGuestBanDrop.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GadgetGuestBanDropReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhHYWRnZXRHdWVzdEJhbkRyb3AucHJvdG8SDW1pSG9tby5Qcm90b3MqbAoS",
            "R2FkZ2V0R3Vlc3RCYW5Ecm9wEhkKFUdBREdFVF9HVUVTVF9CQU5fTk9ORRAA",
            "EhwKGEdBREdFVF9HVUVTVF9CQU5fRElFX0xVQRABEh0KGUdBREdFVF9HVUVT",
            "VF9CQU5fU1VCRklFTEQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MiHomo.Protos.GadgetGuestBanDrop), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GadgetGuestBanDrop {
    [pbr::OriginalName("GADGET_GUEST_BAN_NONE")] GadgetGuestBanNone = 0,
    [pbr::OriginalName("GADGET_GUEST_BAN_DIE_LUA")] GadgetGuestBanDieLua = 1,
    [pbr::OriginalName("GADGET_GUEST_BAN_SUBFIELD")] GadgetGuestBanSubfield = 2,
  }

  #endregion

}

#endregion Designer generated code
