// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GCGLevelType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from GCGLevelType.proto</summary>
  public static partial class GCGLevelTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for GCGLevelType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GCGLevelTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJHQ0dMZXZlbFR5cGUucHJvdG8SDW1pSG9tby5Qcm90b3Mq/wEKDEdDR0xl",
            "dmVsVHlwZRIXChNHQ0dfTEVWRUxfVFlQRV9OT05FEAASGAoUR0NHX0xFVkVM",
            "X1RZUEVfQ09OU1QQARIXChNHQ0dfTEVWRUxfVFlQRV9XRUVLEAISGAoUR0NH",
            "X0xFVkVMX1RZUEVfV09STEQQAxIXChNHQ0dfTEVWRUxfVFlQRV9CT1NTEAQS",
            "HAoYR0NHX0xFVkVMX1RZUEVfQ0hBUkFDVEVSEAUSGAoUR0NHX0xFVkVMX1RZ",
            "UEVfQlJFQUsQBhIYChRHQ0dfTEVWRUxfVFlQRV9RVUVTVBAHEh4KGkdDR19M",
            "RVZFTF9UWVBFX0dVSURFX0dST1VQEAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MiHomo.Protos.GCGLevelType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GCGLevelType {
    [pbr::OriginalName("GCG_LEVEL_TYPE_NONE")] None = 0,
    [pbr::OriginalName("GCG_LEVEL_TYPE_CONST")] Const = 1,
    [pbr::OriginalName("GCG_LEVEL_TYPE_WEEK")] Week = 2,
    [pbr::OriginalName("GCG_LEVEL_TYPE_WORLD")] World = 3,
    [pbr::OriginalName("GCG_LEVEL_TYPE_BOSS")] Boss = 4,
    [pbr::OriginalName("GCG_LEVEL_TYPE_CHARACTER")] Character = 5,
    [pbr::OriginalName("GCG_LEVEL_TYPE_BREAK")] Break = 6,
    [pbr::OriginalName("GCG_LEVEL_TYPE_QUEST")] Quest = 7,
    [pbr::OriginalName("GCG_LEVEL_TYPE_GUIDE_GROUP")] GuideGroup = 8,
  }

  #endregion

}

#endregion Designer generated code
