// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LuaShellType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from LuaShellType.proto</summary>
  public static partial class LuaShellTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for LuaShellType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LuaShellTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJMdWFTaGVsbFR5cGUucHJvdG8SDW1pSG9tby5Qcm90b3MqZgoMTHVhU2hl",
            "bGxUeXBlEhEKDUxVQVNIRUxMX05PTkUQABITCg9MVUFTSEVMTF9OT1JNQUwQ",
            "ARIVChFMVUFTSEVMTF9TRUNVUklUWRACEhcKE0xVQVNIRUxMX1NIRUxMX0NP",
            "REUQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MiHomo.Protos.LuaShellType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LuaShellType {
    [pbr::OriginalName("LUASHELL_NONE")] LuashellNone = 0,
    [pbr::OriginalName("LUASHELL_NORMAL")] LuashellNormal = 1,
    [pbr::OriginalName("LUASHELL_SECURITY")] LuashellSecurity = 2,
    [pbr::OriginalName("LUASHELL_SHELL_CODE")] LuashellShellCode = 3,
  }

  #endregion

}

#endregion Designer generated code
