// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MatchReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from MatchReason.proto</summary>
  public static partial class MatchReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for MatchReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNYXRjaFJlYXNvbi5wcm90bxINbWlIb21vLlByb3RvcyrrAQoLTWF0Y2hS",
            "ZWFzb24SDgoKTUFUQ0hfTk9ORRAAEhAKDE1BVENIX0ZJTklTSBABEhcKE01B",
            "VENIX1BMQVlFUl9DQU5DRUwQAhIRCg1NQVRDSF9USU1FT1VUEAMSGAoUTUFU",
            "Q0hfUExBWUVSX0NPTkZJUk0QBBIQCgxNQVRDSF9GQUlMRUQQBRIWChJNQVRD",
            "SF9TWVNURU1fRVJST1IQBhIVChFNQVRDSF9JTlRFUlJVUFRFRBAHEhgKFE1B",
            "VENIX01QX1VOQVZBSUxBQkxFEAgSGQoVTUFUQ0hfQ09ORklSTV9USU1FT1VU",
            "EAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MiHomo.Protos.MatchReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MatchReason {
    [pbr::OriginalName("MATCH_NONE")] MatchNone = 0,
    [pbr::OriginalName("MATCH_FINISH")] MatchFinish = 1,
    [pbr::OriginalName("MATCH_PLAYER_CANCEL")] MatchPlayerCancel = 2,
    [pbr::OriginalName("MATCH_TIMEOUT")] MatchTimeout = 3,
    [pbr::OriginalName("MATCH_PLAYER_CONFIRM")] MatchPlayerConfirm = 4,
    [pbr::OriginalName("MATCH_FAILED")] MatchFailed = 5,
    [pbr::OriginalName("MATCH_SYSTEM_ERROR")] MatchSystemError = 6,
    [pbr::OriginalName("MATCH_INTERRUPTED")] MatchInterrupted = 7,
    [pbr::OriginalName("MATCH_MP_UNAVAILABLE")] MatchMpUnavailable = 8,
    [pbr::OriginalName("MATCH_CONFIRM_TIMEOUT")] MatchConfirmTimeout = 9,
  }

  #endregion

}

#endregion Designer generated code
