// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MaterialDeleteInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from MaterialDeleteInfo.proto</summary>
  public static partial class MaterialDeleteInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for MaterialDeleteInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MaterialDeleteInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhNYXRlcmlhbERlbGV0ZUluZm8ucHJvdG8SDW1pSG9tby5Qcm90b3MitQYK",
            "Ek1hdGVyaWFsRGVsZXRlSW5mbxIZChFoYXNfZGVsZXRlX2NvbmZpZxgBIAEo",
            "CBJOChFjb3VudF9kb3duX2RlbGV0ZRgCIAEoCzIxLm1pSG9tby5Qcm90b3Mu",
            "TWF0ZXJpYWxEZWxldGVJbmZvLkNvdW50RG93bkRlbGV0ZUgAEkcKC2RhdGVf",
            "ZGVsZXRlGAMgASgLMjAubWlIb21vLlByb3Rvcy5NYXRlcmlhbERlbGV0ZUlu",
            "Zm8uRGF0ZVRpbWVEZWxldGVIABJiChxkZWxheV93ZWVrX2NvdW50X2Rvd25f",
            "ZGVsZXRlGAQgASgLMjoubWlIb21vLlByb3Rvcy5NYXRlcmlhbERlbGV0ZUlu",
            "Zm8uRGVsYXlXZWVrQ291bnREb3duRGVsZXRlSAAa0AEKD0NvdW50RG93bkRl",
            "bGV0ZRIeChZjb25maWdfY291bnRfZG93bl90aW1lGAIgASgNEmQKE2RlbGV0",
            "ZV90aW1lX251bV9tYXAYASADKAsyRy5taUhvbW8uUHJvdG9zLk1hdGVyaWFs",
            "RGVsZXRlSW5mby5Db3VudERvd25EZWxldGUuRGVsZXRlVGltZU51bU1hcEVu",
            "dHJ5GjcKFURlbGV0ZVRpbWVOdW1NYXBFbnRyeRILCgNrZXkYASABKA0SDQoF",
            "dmFsdWUYAiABKA06AjgBGiUKDkRhdGVUaW1lRGVsZXRlEhMKC2RlbGV0ZV90",
            "aW1lGAEgASgNGv0BChhEZWxheVdlZWtDb3VudERvd25EZWxldGUSHgoWY29u",
            "ZmlnX2NvdW50X2Rvd25fdGltZRgDIAEoDRIZChFjb25maWdfZGVsYXlfd2Vl",
            "axgCIAEoDRJtChNkZWxldGVfdGltZV9udW1fbWFwGAEgAygLMlAubWlIb21v",
            "LlByb3Rvcy5NYXRlcmlhbERlbGV0ZUluZm8uRGVsYXlXZWVrQ291bnREb3du",
            "RGVsZXRlLkRlbGV0ZVRpbWVOdW1NYXBFbnRyeRo3ChVEZWxldGVUaW1lTnVt",
            "TWFwRW50cnkSCwoDa2V5GAEgASgNEg0KBXZhbHVlGAIgASgNOgI4AUINCgtk",
            "ZWxldGVfaW5mb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.MaterialDeleteInfo), global::MiHomo.Protos.MaterialDeleteInfo.Parser, new[]{ "HasDeleteConfig", "CountDownDelete", "DateDelete", "DelayWeekCountDownDelete" }, new[]{ "DeleteInfo" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete), global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete.Parser, new[]{ "ConfigCountDownTime", "DeleteTimeNumMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete), global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete.Parser, new[]{ "DeleteTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete), global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete.Parser, new[]{ "ConfigCountDownTime", "ConfigDelayWeek", "DeleteTimeNumMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MaterialDeleteInfo : pb::IMessage<MaterialDeleteInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MaterialDeleteInfo> _parser = new pb::MessageParser<MaterialDeleteInfo>(() => new MaterialDeleteInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MaterialDeleteInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MiHomo.Protos.MaterialDeleteInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MaterialDeleteInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MaterialDeleteInfo(MaterialDeleteInfo other) : this() {
      hasDeleteConfig_ = other.hasDeleteConfig_;
      switch (other.DeleteInfoCase) {
        case DeleteInfoOneofCase.CountDownDelete:
          CountDownDelete = other.CountDownDelete.Clone();
          break;
        case DeleteInfoOneofCase.DateDelete:
          DateDelete = other.DateDelete.Clone();
          break;
        case DeleteInfoOneofCase.DelayWeekCountDownDelete:
          DelayWeekCountDownDelete = other.DelayWeekCountDownDelete.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MaterialDeleteInfo Clone() {
      return new MaterialDeleteInfo(this);
    }

    /// <summary>Field number for the "has_delete_config" field.</summary>
    public const int HasDeleteConfigFieldNumber = 1;
    private bool hasDeleteConfig_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeleteConfig {
      get { return hasDeleteConfig_; }
      set {
        hasDeleteConfig_ = value;
      }
    }

    /// <summary>Field number for the "count_down_delete" field.</summary>
    public const int CountDownDeleteFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete CountDownDelete {
      get { return deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete ? (global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete) deleteInfo_ : null; }
      set {
        deleteInfo_ = value;
        deleteInfoCase_ = value == null ? DeleteInfoOneofCase.None : DeleteInfoOneofCase.CountDownDelete;
      }
    }

    /// <summary>Field number for the "date_delete" field.</summary>
    public const int DateDeleteFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete DateDelete {
      get { return deleteInfoCase_ == DeleteInfoOneofCase.DateDelete ? (global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete) deleteInfo_ : null; }
      set {
        deleteInfo_ = value;
        deleteInfoCase_ = value == null ? DeleteInfoOneofCase.None : DeleteInfoOneofCase.DateDelete;
      }
    }

    /// <summary>Field number for the "delay_week_count_down_delete" field.</summary>
    public const int DelayWeekCountDownDeleteFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete DelayWeekCountDownDelete {
      get { return deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete ? (global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete) deleteInfo_ : null; }
      set {
        deleteInfo_ = value;
        deleteInfoCase_ = value == null ? DeleteInfoOneofCase.None : DeleteInfoOneofCase.DelayWeekCountDownDelete;
      }
    }

    private object deleteInfo_;
    /// <summary>Enum of possible cases for the "delete_info" oneof.</summary>
    public enum DeleteInfoOneofCase {
      None = 0,
      CountDownDelete = 2,
      DateDelete = 3,
      DelayWeekCountDownDelete = 4,
    }
    private DeleteInfoOneofCase deleteInfoCase_ = DeleteInfoOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteInfoOneofCase DeleteInfoCase {
      get { return deleteInfoCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeleteInfo() {
      deleteInfoCase_ = DeleteInfoOneofCase.None;
      deleteInfo_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MaterialDeleteInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MaterialDeleteInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HasDeleteConfig != other.HasDeleteConfig) return false;
      if (!object.Equals(CountDownDelete, other.CountDownDelete)) return false;
      if (!object.Equals(DateDelete, other.DateDelete)) return false;
      if (!object.Equals(DelayWeekCountDownDelete, other.DelayWeekCountDownDelete)) return false;
      if (DeleteInfoCase != other.DeleteInfoCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDeleteConfig != false) hash ^= HasDeleteConfig.GetHashCode();
      if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) hash ^= CountDownDelete.GetHashCode();
      if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) hash ^= DateDelete.GetHashCode();
      if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) hash ^= DelayWeekCountDownDelete.GetHashCode();
      hash ^= (int) deleteInfoCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDeleteConfig != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasDeleteConfig);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) {
        output.WriteRawTag(18);
        output.WriteMessage(CountDownDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) {
        output.WriteRawTag(26);
        output.WriteMessage(DateDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) {
        output.WriteRawTag(34);
        output.WriteMessage(DelayWeekCountDownDelete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDeleteConfig != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasDeleteConfig);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) {
        output.WriteRawTag(18);
        output.WriteMessage(CountDownDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) {
        output.WriteRawTag(26);
        output.WriteMessage(DateDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) {
        output.WriteRawTag(34);
        output.WriteMessage(DelayWeekCountDownDelete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDeleteConfig != false) {
        size += 1 + 1;
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountDownDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateDelete);
      }
      if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DelayWeekCountDownDelete);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MaterialDeleteInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasDeleteConfig != false) {
        HasDeleteConfig = other.HasDeleteConfig;
      }
      switch (other.DeleteInfoCase) {
        case DeleteInfoOneofCase.CountDownDelete:
          if (CountDownDelete == null) {
            CountDownDelete = new global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete();
          }
          CountDownDelete.MergeFrom(other.CountDownDelete);
          break;
        case DeleteInfoOneofCase.DateDelete:
          if (DateDelete == null) {
            DateDelete = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete();
          }
          DateDelete.MergeFrom(other.DateDelete);
          break;
        case DeleteInfoOneofCase.DelayWeekCountDownDelete:
          if (DelayWeekCountDownDelete == null) {
            DelayWeekCountDownDelete = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete();
          }
          DelayWeekCountDownDelete.MergeFrom(other.DelayWeekCountDownDelete);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HasDeleteConfig = input.ReadBool();
            break;
          }
          case 18: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) {
              subBuilder.MergeFrom(CountDownDelete);
            }
            input.ReadMessage(subBuilder);
            CountDownDelete = subBuilder;
            break;
          }
          case 26: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) {
              subBuilder.MergeFrom(DateDelete);
            }
            input.ReadMessage(subBuilder);
            DateDelete = subBuilder;
            break;
          }
          case 34: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) {
              subBuilder.MergeFrom(DelayWeekCountDownDelete);
            }
            input.ReadMessage(subBuilder);
            DelayWeekCountDownDelete = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HasDeleteConfig = input.ReadBool();
            break;
          }
          case 18: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.CountDownDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.CountDownDelete) {
              subBuilder.MergeFrom(CountDownDelete);
            }
            input.ReadMessage(subBuilder);
            CountDownDelete = subBuilder;
            break;
          }
          case 26: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DateTimeDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.DateDelete) {
              subBuilder.MergeFrom(DateDelete);
            }
            input.ReadMessage(subBuilder);
            DateDelete = subBuilder;
            break;
          }
          case 34: {
            global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete subBuilder = new global::MiHomo.Protos.MaterialDeleteInfo.Types.DelayWeekCountDownDelete();
            if (deleteInfoCase_ == DeleteInfoOneofCase.DelayWeekCountDownDelete) {
              subBuilder.MergeFrom(DelayWeekCountDownDelete);
            }
            input.ReadMessage(subBuilder);
            DelayWeekCountDownDelete = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MaterialDeleteInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class CountDownDelete : pb::IMessage<CountDownDelete>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CountDownDelete> _parser = new pb::MessageParser<CountDownDelete>(() => new CountDownDelete());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CountDownDelete> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::MiHomo.Protos.MaterialDeleteInfo.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CountDownDelete() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CountDownDelete(CountDownDelete other) : this() {
          configCountDownTime_ = other.configCountDownTime_;
          deleteTimeNumMap_ = other.deleteTimeNumMap_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CountDownDelete Clone() {
          return new CountDownDelete(this);
        }

        /// <summary>Field number for the "config_count_down_time" field.</summary>
        public const int ConfigCountDownTimeFieldNumber = 2;
        private uint configCountDownTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ConfigCountDownTime {
          get { return configCountDownTime_; }
          set {
            configCountDownTime_ = value;
          }
        }

        /// <summary>Field number for the "delete_time_num_map" field.</summary>
        public const int DeleteTimeNumMapFieldNumber = 1;
        private static readonly pbc::MapField<uint, uint>.Codec _map_deleteTimeNumMap_codec
            = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 10);
        private readonly pbc::MapField<uint, uint> deleteTimeNumMap_ = new pbc::MapField<uint, uint>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<uint, uint> DeleteTimeNumMap {
          get { return deleteTimeNumMap_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CountDownDelete);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CountDownDelete other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ConfigCountDownTime != other.ConfigCountDownTime) return false;
          if (!DeleteTimeNumMap.Equals(other.DeleteTimeNumMap)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ConfigCountDownTime != 0) hash ^= ConfigCountDownTime.GetHashCode();
          hash ^= DeleteTimeNumMap.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          deleteTimeNumMap_.WriteTo(output, _map_deleteTimeNumMap_codec);
          if (ConfigCountDownTime != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ConfigCountDownTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          deleteTimeNumMap_.WriteTo(ref output, _map_deleteTimeNumMap_codec);
          if (ConfigCountDownTime != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ConfigCountDownTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ConfigCountDownTime != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConfigCountDownTime);
          }
          size += deleteTimeNumMap_.CalculateSize(_map_deleteTimeNumMap_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CountDownDelete other) {
          if (other == null) {
            return;
          }
          if (other.ConfigCountDownTime != 0) {
            ConfigCountDownTime = other.ConfigCountDownTime;
          }
          deleteTimeNumMap_.Add(other.deleteTimeNumMap_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                deleteTimeNumMap_.AddEntriesFrom(input, _map_deleteTimeNumMap_codec);
                break;
              }
              case 16: {
                ConfigCountDownTime = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                deleteTimeNumMap_.AddEntriesFrom(ref input, _map_deleteTimeNumMap_codec);
                break;
              }
              case 16: {
                ConfigCountDownTime = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class DateTimeDelete : pb::IMessage<DateTimeDelete>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<DateTimeDelete> _parser = new pb::MessageParser<DateTimeDelete>(() => new DateTimeDelete());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<DateTimeDelete> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::MiHomo.Protos.MaterialDeleteInfo.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DateTimeDelete() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DateTimeDelete(DateTimeDelete other) : this() {
          deleteTime_ = other.deleteTime_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DateTimeDelete Clone() {
          return new DateTimeDelete(this);
        }

        /// <summary>Field number for the "delete_time" field.</summary>
        public const int DeleteTimeFieldNumber = 1;
        private uint deleteTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint DeleteTime {
          get { return deleteTime_; }
          set {
            deleteTime_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as DateTimeDelete);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(DateTimeDelete other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (DeleteTime != other.DeleteTime) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (DeleteTime != 0) hash ^= DeleteTime.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (DeleteTime != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(DeleteTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (DeleteTime != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(DeleteTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (DeleteTime != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeleteTime);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(DateTimeDelete other) {
          if (other == null) {
            return;
          }
          if (other.DeleteTime != 0) {
            DeleteTime = other.DeleteTime;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                DeleteTime = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                DeleteTime = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class DelayWeekCountDownDelete : pb::IMessage<DelayWeekCountDownDelete>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<DelayWeekCountDownDelete> _parser = new pb::MessageParser<DelayWeekCountDownDelete>(() => new DelayWeekCountDownDelete());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<DelayWeekCountDownDelete> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::MiHomo.Protos.MaterialDeleteInfo.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DelayWeekCountDownDelete() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DelayWeekCountDownDelete(DelayWeekCountDownDelete other) : this() {
          configCountDownTime_ = other.configCountDownTime_;
          configDelayWeek_ = other.configDelayWeek_;
          deleteTimeNumMap_ = other.deleteTimeNumMap_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DelayWeekCountDownDelete Clone() {
          return new DelayWeekCountDownDelete(this);
        }

        /// <summary>Field number for the "config_count_down_time" field.</summary>
        public const int ConfigCountDownTimeFieldNumber = 3;
        private uint configCountDownTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ConfigCountDownTime {
          get { return configCountDownTime_; }
          set {
            configCountDownTime_ = value;
          }
        }

        /// <summary>Field number for the "config_delay_week" field.</summary>
        public const int ConfigDelayWeekFieldNumber = 2;
        private uint configDelayWeek_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ConfigDelayWeek {
          get { return configDelayWeek_; }
          set {
            configDelayWeek_ = value;
          }
        }

        /// <summary>Field number for the "delete_time_num_map" field.</summary>
        public const int DeleteTimeNumMapFieldNumber = 1;
        private static readonly pbc::MapField<uint, uint>.Codec _map_deleteTimeNumMap_codec
            = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 10);
        private readonly pbc::MapField<uint, uint> deleteTimeNumMap_ = new pbc::MapField<uint, uint>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<uint, uint> DeleteTimeNumMap {
          get { return deleteTimeNumMap_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as DelayWeekCountDownDelete);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(DelayWeekCountDownDelete other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ConfigCountDownTime != other.ConfigCountDownTime) return false;
          if (ConfigDelayWeek != other.ConfigDelayWeek) return false;
          if (!DeleteTimeNumMap.Equals(other.DeleteTimeNumMap)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ConfigCountDownTime != 0) hash ^= ConfigCountDownTime.GetHashCode();
          if (ConfigDelayWeek != 0) hash ^= ConfigDelayWeek.GetHashCode();
          hash ^= DeleteTimeNumMap.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          deleteTimeNumMap_.WriteTo(output, _map_deleteTimeNumMap_codec);
          if (ConfigDelayWeek != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ConfigDelayWeek);
          }
          if (ConfigCountDownTime != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ConfigCountDownTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          deleteTimeNumMap_.WriteTo(ref output, _map_deleteTimeNumMap_codec);
          if (ConfigDelayWeek != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(ConfigDelayWeek);
          }
          if (ConfigCountDownTime != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ConfigCountDownTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ConfigCountDownTime != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConfigCountDownTime);
          }
          if (ConfigDelayWeek != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConfigDelayWeek);
          }
          size += deleteTimeNumMap_.CalculateSize(_map_deleteTimeNumMap_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(DelayWeekCountDownDelete other) {
          if (other == null) {
            return;
          }
          if (other.ConfigCountDownTime != 0) {
            ConfigCountDownTime = other.ConfigCountDownTime;
          }
          if (other.ConfigDelayWeek != 0) {
            ConfigDelayWeek = other.ConfigDelayWeek;
          }
          deleteTimeNumMap_.Add(other.deleteTimeNumMap_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                deleteTimeNumMap_.AddEntriesFrom(input, _map_deleteTimeNumMap_codec);
                break;
              }
              case 16: {
                ConfigDelayWeek = input.ReadUInt32();
                break;
              }
              case 24: {
                ConfigCountDownTime = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                deleteTimeNumMap_.AddEntriesFrom(ref input, _map_deleteTimeNumMap_codec);
                break;
              }
              case 16: {
                ConfigDelayWeek = input.ReadUInt32();
                break;
              }
              case 24: {
                ConfigCountDownTime = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
