// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResinCardDataUpdateNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from ResinCardDataUpdateNotify.proto</summary>
  public static partial class ResinCardDataUpdateNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for ResinCardDataUpdateNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResinCardDataUpdateNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9SZXNpbkNhcmREYXRhVXBkYXRlTm90aWZ5LnByb3RvEg1taUhvbW8uUHJv",
            "dG9zGhNSZXNpbkNhcmREYXRhLnByb3RvImsKGVJlc2luQ2FyZERhdGFVcGRh",
            "dGVOb3RpZnkSNAoOY2FyZF9kYXRhX2xpc3QYDiADKAsyHC5taUhvbW8uUHJv",
            "dG9zLlJlc2luQ2FyZERhdGESGAoQdG9kYXlfc3RhcnRfdGltZRgEIAEoDWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MiHomo.Protos.ResinCardDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.ResinCardDataUpdateNotify), global::MiHomo.Protos.ResinCardDataUpdateNotify.Parser, new[]{ "CardDataList", "TodayStartTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResinCardDataUpdateNotify : pb::IMessage<ResinCardDataUpdateNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResinCardDataUpdateNotify> _parser = new pb::MessageParser<ResinCardDataUpdateNotify>(() => new ResinCardDataUpdateNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResinCardDataUpdateNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MiHomo.Protos.ResinCardDataUpdateNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResinCardDataUpdateNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResinCardDataUpdateNotify(ResinCardDataUpdateNotify other) : this() {
      cardDataList_ = other.cardDataList_.Clone();
      todayStartTime_ = other.todayStartTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResinCardDataUpdateNotify Clone() {
      return new ResinCardDataUpdateNotify(this);
    }

    /// <summary>Field number for the "card_data_list" field.</summary>
    public const int CardDataListFieldNumber = 14;
    private static readonly pb::FieldCodec<global::MiHomo.Protos.ResinCardData> _repeated_cardDataList_codec
        = pb::FieldCodec.ForMessage(114, global::MiHomo.Protos.ResinCardData.Parser);
    private readonly pbc::RepeatedField<global::MiHomo.Protos.ResinCardData> cardDataList_ = new pbc::RepeatedField<global::MiHomo.Protos.ResinCardData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MiHomo.Protos.ResinCardData> CardDataList {
      get { return cardDataList_; }
    }

    /// <summary>Field number for the "today_start_time" field.</summary>
    public const int TodayStartTimeFieldNumber = 4;
    private uint todayStartTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TodayStartTime {
      get { return todayStartTime_; }
      set {
        todayStartTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResinCardDataUpdateNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResinCardDataUpdateNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!cardDataList_.Equals(other.cardDataList_)) return false;
      if (TodayStartTime != other.TodayStartTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= cardDataList_.GetHashCode();
      if (TodayStartTime != 0) hash ^= TodayStartTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TodayStartTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TodayStartTime);
      }
      cardDataList_.WriteTo(output, _repeated_cardDataList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TodayStartTime != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TodayStartTime);
      }
      cardDataList_.WriteTo(ref output, _repeated_cardDataList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += cardDataList_.CalculateSize(_repeated_cardDataList_codec);
      if (TodayStartTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TodayStartTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResinCardDataUpdateNotify other) {
      if (other == null) {
        return;
      }
      cardDataList_.Add(other.cardDataList_);
      if (other.TodayStartTime != 0) {
        TodayStartTime = other.TodayStartTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32: {
            TodayStartTime = input.ReadUInt32();
            break;
          }
          case 114: {
            cardDataList_.AddEntriesFrom(input, _repeated_cardDataList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32: {
            TodayStartTime = input.ReadUInt32();
            break;
          }
          case 114: {
            cardDataList_.AddEntriesFrom(ref input, _repeated_cardDataList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
