// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WinterCampActivityDetailInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MiHomo.Protos {

  /// <summary>Holder for reflection information generated from WinterCampActivityDetailInfo.proto</summary>
  public static partial class WinterCampActivityDetailInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for WinterCampActivityDetailInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WinterCampActivityDetailInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJXaW50ZXJDYW1wQWN0aXZpdHlEZXRhaWxJbmZvLnByb3RvEg1taUhvbW8u",
            "UHJvdG9zGg9JdGVtUGFyYW0ucHJvdG8aHVdpbnRlckNhbXBSYWNlU3RhZ2VJ",
            "bmZvLnByb3RvGhlXaW50ZXJDYW1wU3RhZ2VJbmZvLnByb3RvIvkCChxXaW50",
            "ZXJDYW1wQWN0aXZpdHlEZXRhaWxJbmZvEjcKC2JhdHRsZV9pbmZvGAogASgL",
            "MiIubWlIb21vLlByb3Rvcy5XaW50ZXJDYW1wU3RhZ2VJbmZvEiAKGGJhdHRs",
            "ZV90YWtlbl9yZXdhcmRfbGlzdBgOIAMoDRI4CgxleHBsb3JlX2luZm8YCyAB",
            "KAsyIi5taUhvbW8uUHJvdG9zLldpbnRlckNhbXBTdGFnZUluZm8SIQoZZXhw",
            "bG9yZV90YWtlbl9yZXdhcmRfbGlzdBgGIAMoDRIZChFpc19jb250ZW50X2Ns",
            "b3NlZBgPIAEoCBI+Cg5yYWNlX2luZm9fbGlzdBgJIAMoCzImLm1pSG9tby5Q",
            "cm90b3MuV2ludGVyQ2FtcFJhY2VTdGFnZUluZm8SMAoOdXNlZF9pdGVtX2xp",
            "c3QYAiADKAsyGC5taUhvbW8uUHJvdG9zLkl0ZW1QYXJhbRIUCgx3aXNoX2lk",
            "X2xpc3QYCCADKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MiHomo.Protos.ItemParamReflection.Descriptor, global::MiHomo.Protos.WinterCampRaceStageInfoReflection.Descriptor, global::MiHomo.Protos.WinterCampStageInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MiHomo.Protos.WinterCampActivityDetailInfo), global::MiHomo.Protos.WinterCampActivityDetailInfo.Parser, new[]{ "BattleInfo", "BattleTakenRewardList", "ExploreInfo", "ExploreTakenRewardList", "IsContentClosed", "RaceInfoList", "UsedItemList", "WishIdList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WinterCampActivityDetailInfo : pb::IMessage<WinterCampActivityDetailInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WinterCampActivityDetailInfo> _parser = new pb::MessageParser<WinterCampActivityDetailInfo>(() => new WinterCampActivityDetailInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WinterCampActivityDetailInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MiHomo.Protos.WinterCampActivityDetailInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WinterCampActivityDetailInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WinterCampActivityDetailInfo(WinterCampActivityDetailInfo other) : this() {
      battleInfo_ = other.battleInfo_ != null ? other.battleInfo_.Clone() : null;
      battleTakenRewardList_ = other.battleTakenRewardList_.Clone();
      exploreInfo_ = other.exploreInfo_ != null ? other.exploreInfo_.Clone() : null;
      exploreTakenRewardList_ = other.exploreTakenRewardList_.Clone();
      isContentClosed_ = other.isContentClosed_;
      raceInfoList_ = other.raceInfoList_.Clone();
      usedItemList_ = other.usedItemList_.Clone();
      wishIdList_ = other.wishIdList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WinterCampActivityDetailInfo Clone() {
      return new WinterCampActivityDetailInfo(this);
    }

    /// <summary>Field number for the "battle_info" field.</summary>
    public const int BattleInfoFieldNumber = 10;
    private global::MiHomo.Protos.WinterCampStageInfo battleInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MiHomo.Protos.WinterCampStageInfo BattleInfo {
      get { return battleInfo_; }
      set {
        battleInfo_ = value;
      }
    }

    /// <summary>Field number for the "battle_taken_reward_list" field.</summary>
    public const int BattleTakenRewardListFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_battleTakenRewardList_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> battleTakenRewardList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> BattleTakenRewardList {
      get { return battleTakenRewardList_; }
    }

    /// <summary>Field number for the "explore_info" field.</summary>
    public const int ExploreInfoFieldNumber = 11;
    private global::MiHomo.Protos.WinterCampStageInfo exploreInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MiHomo.Protos.WinterCampStageInfo ExploreInfo {
      get { return exploreInfo_; }
      set {
        exploreInfo_ = value;
      }
    }

    /// <summary>Field number for the "explore_taken_reward_list" field.</summary>
    public const int ExploreTakenRewardListFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_exploreTakenRewardList_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> exploreTakenRewardList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ExploreTakenRewardList {
      get { return exploreTakenRewardList_; }
    }

    /// <summary>Field number for the "is_content_closed" field.</summary>
    public const int IsContentClosedFieldNumber = 15;
    private bool isContentClosed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsContentClosed {
      get { return isContentClosed_; }
      set {
        isContentClosed_ = value;
      }
    }

    /// <summary>Field number for the "race_info_list" field.</summary>
    public const int RaceInfoListFieldNumber = 9;
    private static readonly pb::FieldCodec<global::MiHomo.Protos.WinterCampRaceStageInfo> _repeated_raceInfoList_codec
        = pb::FieldCodec.ForMessage(74, global::MiHomo.Protos.WinterCampRaceStageInfo.Parser);
    private readonly pbc::RepeatedField<global::MiHomo.Protos.WinterCampRaceStageInfo> raceInfoList_ = new pbc::RepeatedField<global::MiHomo.Protos.WinterCampRaceStageInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MiHomo.Protos.WinterCampRaceStageInfo> RaceInfoList {
      get { return raceInfoList_; }
    }

    /// <summary>Field number for the "used_item_list" field.</summary>
    public const int UsedItemListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MiHomo.Protos.ItemParam> _repeated_usedItemList_codec
        = pb::FieldCodec.ForMessage(18, global::MiHomo.Protos.ItemParam.Parser);
    private readonly pbc::RepeatedField<global::MiHomo.Protos.ItemParam> usedItemList_ = new pbc::RepeatedField<global::MiHomo.Protos.ItemParam>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MiHomo.Protos.ItemParam> UsedItemList {
      get { return usedItemList_; }
    }

    /// <summary>Field number for the "wish_id_list" field.</summary>
    public const int WishIdListFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_wishIdList_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> wishIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> WishIdList {
      get { return wishIdList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WinterCampActivityDetailInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WinterCampActivityDetailInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BattleInfo, other.BattleInfo)) return false;
      if(!battleTakenRewardList_.Equals(other.battleTakenRewardList_)) return false;
      if (!object.Equals(ExploreInfo, other.ExploreInfo)) return false;
      if(!exploreTakenRewardList_.Equals(other.exploreTakenRewardList_)) return false;
      if (IsContentClosed != other.IsContentClosed) return false;
      if(!raceInfoList_.Equals(other.raceInfoList_)) return false;
      if(!usedItemList_.Equals(other.usedItemList_)) return false;
      if(!wishIdList_.Equals(other.wishIdList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (battleInfo_ != null) hash ^= BattleInfo.GetHashCode();
      hash ^= battleTakenRewardList_.GetHashCode();
      if (exploreInfo_ != null) hash ^= ExploreInfo.GetHashCode();
      hash ^= exploreTakenRewardList_.GetHashCode();
      if (IsContentClosed != false) hash ^= IsContentClosed.GetHashCode();
      hash ^= raceInfoList_.GetHashCode();
      hash ^= usedItemList_.GetHashCode();
      hash ^= wishIdList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      usedItemList_.WriteTo(output, _repeated_usedItemList_codec);
      exploreTakenRewardList_.WriteTo(output, _repeated_exploreTakenRewardList_codec);
      wishIdList_.WriteTo(output, _repeated_wishIdList_codec);
      raceInfoList_.WriteTo(output, _repeated_raceInfoList_codec);
      if (battleInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(BattleInfo);
      }
      if (exploreInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(ExploreInfo);
      }
      battleTakenRewardList_.WriteTo(output, _repeated_battleTakenRewardList_codec);
      if (IsContentClosed != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsContentClosed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      usedItemList_.WriteTo(ref output, _repeated_usedItemList_codec);
      exploreTakenRewardList_.WriteTo(ref output, _repeated_exploreTakenRewardList_codec);
      wishIdList_.WriteTo(ref output, _repeated_wishIdList_codec);
      raceInfoList_.WriteTo(ref output, _repeated_raceInfoList_codec);
      if (battleInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(BattleInfo);
      }
      if (exploreInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(ExploreInfo);
      }
      battleTakenRewardList_.WriteTo(ref output, _repeated_battleTakenRewardList_codec);
      if (IsContentClosed != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsContentClosed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (battleInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleInfo);
      }
      size += battleTakenRewardList_.CalculateSize(_repeated_battleTakenRewardList_codec);
      if (exploreInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExploreInfo);
      }
      size += exploreTakenRewardList_.CalculateSize(_repeated_exploreTakenRewardList_codec);
      if (IsContentClosed != false) {
        size += 1 + 1;
      }
      size += raceInfoList_.CalculateSize(_repeated_raceInfoList_codec);
      size += usedItemList_.CalculateSize(_repeated_usedItemList_codec);
      size += wishIdList_.CalculateSize(_repeated_wishIdList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WinterCampActivityDetailInfo other) {
      if (other == null) {
        return;
      }
      if (other.battleInfo_ != null) {
        if (battleInfo_ == null) {
          BattleInfo = new global::MiHomo.Protos.WinterCampStageInfo();
        }
        BattleInfo.MergeFrom(other.BattleInfo);
      }
      battleTakenRewardList_.Add(other.battleTakenRewardList_);
      if (other.exploreInfo_ != null) {
        if (exploreInfo_ == null) {
          ExploreInfo = new global::MiHomo.Protos.WinterCampStageInfo();
        }
        ExploreInfo.MergeFrom(other.ExploreInfo);
      }
      exploreTakenRewardList_.Add(other.exploreTakenRewardList_);
      if (other.IsContentClosed != false) {
        IsContentClosed = other.IsContentClosed;
      }
      raceInfoList_.Add(other.raceInfoList_);
      usedItemList_.Add(other.usedItemList_);
      wishIdList_.Add(other.wishIdList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            usedItemList_.AddEntriesFrom(input, _repeated_usedItemList_codec);
            break;
          }
          case 50:
          case 48: {
            exploreTakenRewardList_.AddEntriesFrom(input, _repeated_exploreTakenRewardList_codec);
            break;
          }
          case 66:
          case 64: {
            wishIdList_.AddEntriesFrom(input, _repeated_wishIdList_codec);
            break;
          }
          case 74: {
            raceInfoList_.AddEntriesFrom(input, _repeated_raceInfoList_codec);
            break;
          }
          case 82: {
            if (battleInfo_ == null) {
              BattleInfo = new global::MiHomo.Protos.WinterCampStageInfo();
            }
            input.ReadMessage(BattleInfo);
            break;
          }
          case 90: {
            if (exploreInfo_ == null) {
              ExploreInfo = new global::MiHomo.Protos.WinterCampStageInfo();
            }
            input.ReadMessage(ExploreInfo);
            break;
          }
          case 114:
          case 112: {
            battleTakenRewardList_.AddEntriesFrom(input, _repeated_battleTakenRewardList_codec);
            break;
          }
          case 120: {
            IsContentClosed = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            usedItemList_.AddEntriesFrom(ref input, _repeated_usedItemList_codec);
            break;
          }
          case 50:
          case 48: {
            exploreTakenRewardList_.AddEntriesFrom(ref input, _repeated_exploreTakenRewardList_codec);
            break;
          }
          case 66:
          case 64: {
            wishIdList_.AddEntriesFrom(ref input, _repeated_wishIdList_codec);
            break;
          }
          case 74: {
            raceInfoList_.AddEntriesFrom(ref input, _repeated_raceInfoList_codec);
            break;
          }
          case 82: {
            if (battleInfo_ == null) {
              BattleInfo = new global::MiHomo.Protos.WinterCampStageInfo();
            }
            input.ReadMessage(BattleInfo);
            break;
          }
          case 90: {
            if (exploreInfo_ == null) {
              ExploreInfo = new global::MiHomo.Protos.WinterCampStageInfo();
            }
            input.ReadMessage(ExploreInfo);
            break;
          }
          case 114:
          case 112: {
            battleTakenRewardList_.AddEntriesFrom(ref input, _repeated_battleTakenRewardList_codec);
            break;
          }
          case 120: {
            IsContentClosed = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
